CREATE DATABASE school_manage;

-- Students Table
CREATE TABLE std (
    id INT AUTO_INCREMENT PRIMARY KEY,
     VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
);
